version: "3"
services:

  backend:
    container_name: lda_backend
    image: lda_backend_img
    build: ./backend
    volumes:
      - ./backend:/app-backend
    restart: always

  frontend:
    container_name: lda_frontend
    image: lda_frontend_img
    build: ./frontend
    volumes:
      - ./frontend:/app-frontend
    ports:
      - 3408:3408
    depends_on:
      - backend
    restart: always

  nginx_backend_server:
    container_name: lda_nginx_backend_server
    image: lda_nginx_backend_server_img
    build: ./nginx_backend_server
    ports:
        - 8408:8408
    depends_on:
        - backend
    restart: always

