# Generated by Django 3.2.13 on 2022-12-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='Binance Isolated Margin', max_length=30),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
