# Generated by Django 3.2.13 on 2022-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0002_auto_20221223_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
