name: Leandro Damasio's Website Production Pipeline

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: | 
            ldamasio/lda-frontend:0.0.${{github.run_number}}
            ldamasio/lda-frontend:latest

      - name: Build and push Docker monolith backend image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: | 
            ldamasio/lda-backend-monolith:1.0.${{github.run_number}}
            ldamasio/lda-backend-monolith:latest
